package feature_products

import kotlinx.serialization.Serializable

object ProductsRepository {
    val productsByCategory: Map<Category, List<Product>> = mapOf(
        Category.VEGETABLES to listOf(
            Product("Tomato", "🍅", 0xFFFFC1C1),
            Product("Cherry Tomato", "🍅", 0xFFFFC1C1),
            Product("Roma Tomato", "🍅", 0xFFFFC1C1),
            Product("Cucumber", "🥒", 0xFFC8E6C9),
            Product("English Cucumber", "🥒", 0xFFC8E6C9),
            Product("Potato", "🥔", 0xFFFFE4C4),
            Product("Sweet Potato", "🍠", 0xFFFFE4C4),
            Product("Russet Potato", "🥔", 0xFFFFE4C4),
            Product("Carrot", "🥕", 0xFFFFDAB9),
            Product("Baby Carrot", "🥕", 0xFFFFDAB9),
            Product("Red Onion", "🧅", 0xFFE1BEE7),
            Product("Yellow Onion", "🧅", 0xFFFFF5E6),
            Product("White Onion", "🧅", 0xFFFFFFFF),
            Product("Green Onion", "🧅", 0xFFC8E6C9),
            Product("Garlic", "🧄", 0xFFFFFFFF),
            Product("Elephant Garlic", "🧄", 0xFFFFFFFF),
            Product("Iceberg Lettuce", "🥬", 0xFFDCEDC8),
            Product("Romaine Lettuce", "🥬", 0xFFDCEDC8),
            Product("Arugula", "🥬", 0xFFC8E6C9),
            Product("Broccoli", "🥦", 0xFFC8E6C9),
            Product("Broccolini", "🥦", 0xFFC8E6C9),
            Product("Eggplant", "🍆", 0xFFE1BEE7),
            Product("Japanese Eggplant", "🍆", 0xFFE1BEE7),
            Product("Bell Pepper", "🫑", 0xFFC8E6C9),
            Product("Red Bell Pepper", "🫑", 0xFFFFC1C1),
            Product("Yellow Bell Pepper", "🫑", 0xFFFFF9C4),
            Product("Green Bell Pepper", "🫑", 0xFFC8E6C9),
            Product("Jalapeño Pepper", "🌶️", 0xFFC8E6C9),
            Product("Habanero Pepper", "🌶️", 0xFFFFCDD2),
            Product("Spinach", "🥬", 0xFFDCEDC8),
            Product("Baby Spinach", "🥬", 0xFFDCEDC8),
            Product("Kale", "🥬", 0xFFC8E6C9),
            Product("Zucchini", "🥒", 0xFFC8E6C9),
            Product("Yellow Squash", "🥒", 0xFFFFF9C4),
            Product("Button Mushroom", "🍄", 0xFFD7CCC8),
            Product("Portobello Mushroom", "🍄", 0xFFD7CCC8),
            Product("Shiitake Mushroom", "🍄", 0xFFD7CCC8),
            Product("Asparagus", "🥦", 0xFFC8E6C9),
            Product("Cauliflower", "🥦", 0xFFFFFFFF),
            Product("Radish", "🫒", 0xFFFFCDD2),
            Product("Beet", "🫒", 0xFFE1BEE7),
            Product("Turnip", "🫒", 0xFFFFFFFF),
            Product("Artichoke", "🫚", 0xFFC8E6C9),
            Product("Brussels Sprout", "🥬", 0xFFC8E6C9),
            Product("Cabbage", "🥬", 0xFFC8E6C9),
            Product("Red Cabbage", "🥬", 0xFFE1BEE7),
            Product("Celery", "🥬", 0xFFC8E6C9),
            Product("Leek", "🧅", 0xFFC8E6C9),
            Product("Fennel", "🫚", 0xFFFFFFFF),
            Product("Bok Choy", "🥬", 0xFFC8E6C9)
        ),
        Category.FRUITS to listOf(
            Product("Red Apple", "🍎", 0xFFFFCDD2),
            Product("Green Apple", "🍏", 0xFFC8E6C9),
            Product("Banana", "🍌", 0xFFFFF9C4),
            Product("Plantain", "🍌", 0xFFFFF9C4),
            Product("Watermelon", "🍉", 0xFFC8E6C9),
            Product("Green Grapes", "🍇", 0xFFC8E6C9),
            Product("Red Grapes", "🍇", 0xFFD1C4E9),
            Product("Pineapple", "🍍", 0xFFFFFFE0),
            Product("Cherry", "🍒", 0xFFFFCDD2),
            Product("Strawberry", "🍓", 0xFFFFCDD2),
            Product("Peach", "🍑", 0xFFFFF5E6),
            Product("Nectarine", "🍑", 0xFFFFF5E6),
            Product("Kiwi", "🥝", 0xFFC8E6C9),
            Product("Orange", "🍊", 0xFFFFE0B2),
            Product("Mandarin", "🍊", 0xFFFFE0B2),
            Product("Lemon", "🍋", 0xFFFFF9C4),
            Product("Lime", "🍋", 0xFFC8E6C9),
            Product("Blueberry", "🫐", 0xFFD1C4E9),
            Product("Raspberry", "🍓", 0xFFFFCDD2),
            Product("Blackberry", "🫐", 0xFFD1C4E9),
            Product("Mango", "🥭", 0xFFFFE0B2),
            Product("Avocado", "🥑", 0xFFC8E6C9),
            Product("Pomegranate", "🍎", 0xFFFFCDD2),
            Product("Pear", "🍐", 0xFFFFF9C4),
            Product("Apricot", "🍑", 0xFFFFF5E6),
            Product("Plum", "🫐", 0xFFE1BEE7),
            Product("Fig", "🫒", 0xFFD7CCC8),
            Product("Coconut", "🥥", 0xFFFFF5E6),
            Product("Papaya", "🥭", 0xFFFFE0B2),
            Product("Guava", "🫒", 0xFFC8E6C9),
            Product("Passion Fruit", "🫒", 0xFFD1C4E9),
            Product("Dragon Fruit", "🫒", 0xFFFFCDD2),
            Product("Lychee", "🫒", 0xFFFFFFFF),
            Product("Cantaloupe", "🍈", 0xFFFFF5E6),
            Product("Honeydew Melon", "🍈", 0xFFC8E6C9),
            Product("Grapefruit", "🍊", 0xFFFFCDD2),
            Product("Persimmon", "🍅", 0xFFFFE0B2),
            Product("Starfruit", "🌟", 0xFFFFF9C4),
            Product("Jackfruit", "🫒", 0xFFFFF9C4),
            Product("Durian", "🫒", 0xFFFFF9C4)
        ),
        Category.DAIRY_AND_EGGS to listOf(
            Product("Whole Milk", "🥛", 0xFFFFFFFF),
            Product("Skim Milk", "🥛", 0xFFFFFFFF),
            Product("Almond Milk", "🥛", 0xFFFFF5E6),
            Product("Soy Milk", "🥛", 0xFFFFF5E6),
            Product("Oat Milk", "🥛", 0xFFFFF5E6),
            Product("Cheddar Cheese", "🧀", 0xFFFFF9C4),
            Product("Mozzarella Cheese", "🧀", 0xFFFFFFFF),
            Product("Parmesan Cheese", "🧀", 0xFFFFF5E6),
            Product("Gouda Cheese", "🧀", 0xFFFFE0B2),
            Product("Brie Cheese", "🧀", 0xFFFFF5E6),
            Product("Feta Cheese", "🧀", 0xFFFFFFFF),
            Product("Blue Cheese", "🧀", 0xFFBBDEFB),
            Product("Goat Cheese", "🧀", 0xFFFFFFFF),
            Product("Swiss Cheese", "🧀", 0xFFFFF5E6),
            Product("Ricotta Cheese", "🧀", 0xFFFFFFFF),
            Product("Chicken Egg", "🥚", 0xFFFFFFE0),
            Product("Quail Egg", "🥚", 0xFFFFF5E6),
            Product("Duck Egg", "🥚", 0xFFFFF5E6),
            Product("Butter", "🧈", 0xFFFFF5E6),
            Product("Margarine", "🧈", 0xFFFFF5E6),
            Product("Greek Yogurt", "🥄", 0xFFFFFFFF),
            Product("Plain Yogurt", "🥄", 0xFFFFFFFF),
            Product("Flavored Yogurt", "🥄", 0xFFFFF5E6),
            Product("Heavy Cream", "🥛", 0xFFFFF5E6),
            Product("Half-and-Half", "🥛", 0xFFFFF5E6),
            Product("Sour Cream", "🥄", 0xFFFFFFFF),
            Product("Cream Cheese", "🧀", 0xFFFFFFFF),
            Product("Cottage Cheese", "🧀", 0xFFFFFFFF),
            Product("Whipped Cream", "🧁", 0xFFFFFFFF),
            Product("Condensed Milk", "🥛", 0xFFFFF5E6),
            Product("Evaporated Milk", "🥛", 0xFFFFF5E6)
        ),
        Category.MEAT_AND_POULTRY to listOf(
            Product("Ribeye Steak", "🥩", 0xFFFFCDD2),
            Product("Sirloin Steak", "🥩", 0xFFFFCDD2),
            Product("T-Bone Steak", "🥩", 0xFFFFCDD2),
            Product("Filet Mignon", "🥩", 0xFFFFCDD2),
            Product("Ground Beef", "🥩", 0xFFFFCDD2),
            Product("Beef Brisket", "🥩", 0xFFFFCDD2),
            Product("Beef Ribs", "🍖", 0xFFFFCDD2),
            Product("Chicken Breast", "🍗", 0xFFFFF3E0),
            Product("Chicken Thigh", "🍗", 0xFFFFF3E0),
            Product("Chicken Wing", "🍗", 0xFFFFF3E0),
            Product("Whole Chicken", "🐔", 0xFFFFF3E0),
            Product("Ground Chicken", "🍗", 0xFFFFF3E0),
            Product("Turkey Breast", "🦃", 0xFFFFF3E0),
            Product("Ground Turkey", "🦃", 0xFFFFF3E0),
            Product("Pork Chop", "🍖", 0xFFFFF3E0),
            Product("Pork Loin", "🍖", 0xFFFFF3E0),
            Product("Pork Belly", "🥓", 0xFFFFE4C4),
            Product("Ground Pork", "🍖", 0xFFFFF3E0),
            Product("Bacon", "🥓", 0xFFFFE4C4),
            Product("Ham", "🍖", 0xFFFFE4C4),
            Product("Lamb Chop", "🍖", 0xFFFFCDD2),
            Product("Lamb Shank", "🍖", 0xFFFFCDD2),
            Product("Ground Lamb", "🍖", 0xFFFFCDD2),
            Product("Veal Cutlet", "🍖", 0xFFFFF3E0),
            Product("Duck Breast", "🦆", 0xFFFFE4C4),
            Product("Goose", "🦢", 0xFFFFF3E0),
            Product("Quail", "🐦", 0xFFFFF3E0),
            Product("Venison", "🦌", 0xFFFFCDD2),
            Product("Bison", "🐃", 0xFFFFCDD2),
            Product("Rabbit", "🐰", 0xFFFFF3E0),
            Product("Sausage", "🌭", 0xFFFFE4C4),
            Product("Salami", "🥖", 0xFFFFE4C4),
            Product("Prosciutto", "🥓", 0xFFFFE4C4),
            Product("Pepperoni", "🍕", 0xFFFFCDD2)
        ),
        Category.SEAFOOD to listOf(
            Product("Salmon", "🐟", 0xFFFFCDD2),
            Product("Tuna", "🐟", 0xFFBBDEFB),
            Product("Cod", "🐟", 0xFFFFFFFF),
            Product("Halibut", "🐟", 0xFFFFFFFF),
            Product("Tilapia", "🐟", 0xFFFFFFFF),
            Product("Trout", "🐟", 0xFFFFDAB9),
            Product("Mahi Mahi", "🐟", 0xFFFFE0B2),
            Product("Sardines", "🐟", 0xFFBBDEFB),
            Product("Anchovies", "🐟", 0xFFBBDEFB),
            Product("Sea Bass", "🐟", 0xFFFFFFFF),
            Product("Catfish", "🐟", 0xFFD7CCC8),
            Product("Swordfish", "🐟", 0xFFFFFFFF),
            Product("Mackerel", "🐟", 0xFFBBDEFB),
            Product("Herring", "🐟", 0xFFBBDEFB),
            Product("Flounder", "🐟", 0xFFFFFFFF),
            Product("Snapper", "🐟", 0xFFFFCDD2),
            Product("Grouper", "🐟", 0xFFFFFFFF),
            Product("Shrimp", "🍤", 0xFFFFE4C4),
            Product("Prawns", "🦐", 0xFFFFE4C4),
            Product("Lobster", "🦞", 0xFFFFCDD2),
            Product("Crab", "🦀", 0xFFFFCDD2),
            Product("Crayfish", "🦞", 0xFFFFCDD2),
            Product("Scallops", "🐚", 0xFFFFF5E6),
            Product("Oysters", "🦪", 0xFFD7CCC8),
            Product("Mussels", "🐚", 0xFFD7CCC8),
            Product("Clams", "🐚", 0xFFFFF5E6),
            Product("Squid", "🦑", 0xFFD1C4E9),
            Product("Octopus", "🐙", 0xFFD1C4E9),
            Product("Caviar", "🫙", 0xFF000000),
            Product("Roe", "🫙", 0xFFFFCDD2)
        ),
        Category.GRAINS_AND_LEGUMES to listOf(
            Product("White Rice", "🍚", 0xFFFFF8E1),
            Product("Brown Rice", "🍚", 0xFFFFE0B2),
            Product("Basmati Rice", "🍚", 0xFFFFF8E1),
            Product("Jasmine Rice", "🍚", 0xFFFFF8E1),
            Product("Wild Rice", "🍚", 0xFFD7CCC8),
            Product("Spaghetti", "🍝", 0xFFFFF3E0),
            Product("Penne", "🍝", 0xFFFFF3E0),
            Product("Fettuccine", "🍝", 0xFFFFF3E0),
            Product("Lasagna", "🍝", 0xFFFFF3E0),
            Product("Macaroni", "🍝", 0xFFFFF3E0),
            Product("Egg Noodles", "🍜", 0xFFFFF3E0),
            Product("Ramen Noodles", "🍜", 0xFFFFF3E0),
            Product("Udon Noodles", "🍜", 0xFFFFFFFF),
            Product("Rice Noodles", "🍜", 0xFFFFFFFF),
            Product("Soba Noodles", "🍜", 0xFFD7CCC8),
            Product("Lo Mein Noodles", "🍜", 0xFFFFE0B2),
            Product("Vermicelli", "🍜", 0xFFFFFFFF),
            Product("Couscous", "🍚", 0xFFFFF8E1),
            Product("Quinoa", "🍚", 0xFFFFF8E1),
            Product("Barley", "🌾", 0xFFFFE0B2),
            Product("Oats", "🥣", 0xFFFFF3E0),
            Product("Buckwheat", "🌾", 0xFFD7CCC8),
            Product("Millet", "🌾", 0xFFFFF9C4),
            Product("Black Beans", "🫘", 0xFF000000),
            Product("Kidney Beans", "🫘", 0xFFD32F2F),
            Product("Pinto Beans", "🫘", 0xFFD7CCC8),
            Product("Chickpeas", "🫘", 0xFFFFF5E6),
            Product("Lentils", "🫘", 0xFFD7CCC8),
            Product("Green Peas", "🫛", 0xFFC8E6C9),
            Product("Soybeans", "🫘", 0xFFFFF5E6),
            Product("Black-eyed Peas", "🫘", 0xFFFFF5E6),
            Product("Lima Beans", "🫘", 0xFFC8E6C9),
            Product("Navy Beans", "🫘", 0xFFFFFFFF),
            Product("Fava Beans", "🫘", 0xFFC8E6C9),
            Product("Split Peas", "🫛", 0xFFFFF5E6),
            Product("Adzuki Beans", "🫘", 0xFFD32F2F)
        ),
        Category.BAKING_AND_COOKING_ESSENTIALS to listOf(
            Product("All-purpose Flour", "🍞", 0xFFFFF5E6),
            Product("Whole Wheat Flour", "🍞", 0xFFFFE0B2),
            Product("Bread Flour", "🍞", 0xFFFFF5E6),
            Product("Cake Flour", "🍰", 0xFFFFFFFF),
            Product("Cornmeal", "🌽", 0xFFFFF9C4),
            Product("Baking Powder", "🧂", 0xFFFFFFFF),
            Product("Baking Soda", "🧂", 0xFFFFFFFF),
            Product("Active Dry Yeast", "🧫", 0xFFFFF5E6),
            Product("Granulated Sugar", "🧂", 0xFFFFFFFF),
            Product("Brown Sugar", "🧂", 0xFFFFE0B2),
            Product("Powdered Sugar", "🧂", 0xFFFFFFFF),
            Product("Honey", "🍯", 0xFFFFF9C4),
            Product("Maple Syrup", "🍯", 0xFFFFE0B2),
            Product("Corn Syrup", "🫙", 0xFFFFF5E6),
            Product("Molasses", "🫙", 0xFF4E342E),
            Product("Vanilla Extract", "🧪", 0xFFFFF3E0),
            Product("Almond Extract", "🧪", 0xFFFFF3E0),
            Product("Olive Oil", "🫒", 0xFFC8E6C9),
            Product("Vegetable Oil", "🫙", 0xFFFFF5E6),
            Product("Coconut Oil", "🥥", 0xFFFFFFFF),
            Product("Canola Oil", "🫙", 0xFFFFF5E6),
            Product("Sesame Oil", "🫙", 0xFFFFE0B2),
            Product("Peanut Oil", "🥜", 0xFFFFE0B2),
            Product("Salt", "🧂", 0xFFFFFFFF),
            Product("Black Pepper", "🧂", 0xFF000000),
            Product("White Pepper", "🧂", 0xFFFFF5E6),
            Product("Red Pepper Flakes", "🌶️", 0xFFFFCDD2),
            Product("Cornstarch", "🫙", 0xFFFFFFFF),
            Product("Cocoa Powder", "🍫", 0xFF4E342E),
            Product("Chocolate Chips", "🍫", 0xFF4E342E)
        ),
        Category.CONDIMENTS_AND_SAUCES to listOf(
            Product("Ketchup", "🍅", 0xFFFFC1C1),
            Product("Mustard", "🌭", 0xFFFFF9C4),
            Product("Mayonnaise", "🥚", 0xFFFFFFFF),
            Product("Soy Sauce", "🍶", 0xFF4E342E),
            Product("Hot Sauce", "🌶️", 0xFFFFCDD2),
            Product("Barbecue Sauce", "🍖", 0xFF4E342E),
            Product("Worcestershire Sauce", "🍶", 0xFF4E342E),
            Product("Sriracha Sauce", "🌶️", 0xFFFF5252),
            Product("Teriyaki Sauce", "🍶", 0xFF4E342E),
            Product("Fish Sauce", "🐟", 0xFFD7CCC8),
            Product("Hoisin Sauce", "🫙", 0xFF4E342E),
            Product("Oyster Sauce", "🦪", 0xFF4E342E),
            Product("Vinegar", "🍶", 0xFFFFF3E0),
            Product("Balsamic Vinegar", "🍶", 0xFF4E342E),
            Product("Apple Cider Vinegar", "🍎", 0xFFFFE0B2),
            Product("Rice Vinegar", "🍚", 0xFFFFF3E0),
            Product("Salad Dressing", "🥗", 0xFFFFF5E6),
            Product("Ranch Dressing", "🥗", 0xFFFFFFFF),
            Product("Italian Dressing", "🥗", 0xFFFFF5E6),
            Product("Caesar Dressing", "🥗", 0xFFFFF5E6),
            Product("Pesto", "🌿", 0xFFC8E6C9),
            Product("Salsa", "🌶️", 0xFFFFC1C1),
            Product("Guacamole", "🥑", 0xFFC8E6C9),
            Product("Hummus", "🫘", 0xFFFFF5E6),
            Product("Tahini", "🫙", 0xFFFFF5E6),
            Product("Horseradish", "🌶️", 0xFFFFFFFF),
            Product("Wasabi", "🍣", 0xFFC8E6C9),
            Product("Chutney", "🫙", 0xFFFFE0B2),
            Product("Tartar Sauce", "🐟", 0xFFFFFFFF),
            Product("Cocktail Sauce", "🍤", 0xFFFFC1C1)
        ),
        Category.SNACKS_AND_SWEETS to listOf(
            Product("Potato Chips", "🥔", 0xFFFFF9C4),
            Product("Tortilla Chips", "🌽", 0xFFFFF9C4),
            Product("Pretzels", "🥨", 0xFFFFE0B2),
            Product("Popcorn", "🍿", 0xFFFFF8E1),
            Product("Peanuts", "🥜", 0xFFFFE0B2),
            Product("Almonds", "🥜", 0xFFFFE0B2),
            Product("Cashews", "🥜", 0xFFFFE0B2),
            Product("Pistachios", "🥜", 0xFFC8E6C9),
            Product("Walnuts", "🌰", 0xFFD7CCC8),
            Product("Pecans", "🌰", 0xFFD7CCC8),
            Product("Trail Mix", "🥜", 0xFFFFE0B2),
            Product("Chocolate Bar", "🍫", 0xFF4E342E),
            Product("Dark Chocolate", "🍫", 0xFF3E2723),
            Product("Milk Chocolate", "🍫", 0xFF795548),
            Product("White Chocolate", "🍫", 0xFFFFF3E0),
            Product("Candy", "🍬", 0xFFFFCDD2),
            Product("Lollipop", "🍭", 0xFFFFCDD2),
            Product("Gummy Bears", "🧸", 0xFFFFCDD2),
            Product("Jelly Beans", "🫘", 0xFFFFCDD2),
            Product("Licorice", "🍬", 0xFF000000),
            Product("Cookie", "🍪", 0xFFFFF3E0),
            Product("Chocolate Chip Cookie", "🍪", 0xFFFFE0B2),
            Product("Oatmeal Cookie", "🍪", 0xFFFFE0B2),
            Product("Brownie", "🍫", 0xFF4E342E),
            Product("Cake", "🍰", 0xFFFFFFFF),
            Product("Cupcake", "🧁", 0xFFFFFFFF),
            Product("Donut", "🍩", 0xFFFFF3E0),
            Product("Ice Cream", "🍦", 0xFFFFFFFF),
            Product("Gelato", "🍨", 0xFFFFFFFF),
            Product("Sorbet", "🍧", 0xFFFFCDD2)
        ),
        Category.CANNED_AND_PRESERVED_GOODS to listOf(
            Product("Canned Tomatoes", "🥫", 0xFFFFC1C1),
            Product("Tomato Paste", "🥫", 0xFFD32F2F),
            Product("Canned Corn", "🥫", 0xFFFFF9C4),
            Product("Canned Green Beans", "🥫", 0xFFC8E6C9),
            Product("Canned Peas", "🥫", 0xFFC8E6C9),
            Product("Canned Carrots", "🥫", 0xFFFFDAB9),
            Product("Canned Mixed Vegetables", "🥫", 0xFFC8E6C9),
            Product("Canned Mushrooms", "🥫", 0xFFD7CCC8),
            Product("Canned Pineapple", "🥫", 0xFFFFFFE0),
            Product("Canned Peaches", "🥫", 0xFFFFF5E6),
            Product("Canned Pears", "🥫", 0xFFFFF5E6),
            Product("Canned Mandarin Oranges", "🥫", 0xFFFFE0B2),
            Product("Canned Tuna", "🐟", 0xFFBBDEFB),
            Product("Canned Salmon", "🐟", 0xFFFFCDD2),
            Product("Canned Sardines", "🐟", 0xFFBBDEFB),
            Product("Canned Chicken", "🥫", 0xFFFFF3E0),
            Product("Canned Beef", "🥫", 0xFFFFCDD2),
            Product("Canned Beans", "🫘", 0xFFD7CCC8),
            Product("Canned Chickpeas", "🫘", 0xFFFFF5E6),
            Product("Canned Lentils", "🫘", 0xFFD7CCC8),
            Product("Canned Soup", "🥣", 0xFFFFE0B2),
            Product("Canned Chili", "🌶️", 0xFFD32F2F),
            Product("Canned Broth", "🥣", 0xFFFFE0B2),
            Product("Pickles", "🥒", 0xFFC8E6C9),
            Product("Olives", "🫒", 0xFF4E342E),
            Product("Sauerkraut", "🥬", 0xFFFFF5E6),
            Product("Kimchi", "🥬", 0xFFFF5252),
            Product("Jam", "🍓", 0xFFFFCDD2),
            Product("Jelly", "🍇", 0xFFD1C4E9),
            Product("Peanut Butter", "🥜", 0xFFFFE0B2),
            Product("Almond Butter", "🥜", 0xFFFFE0B2),
            Product("Nutella", "🍫", 0xFF4E342E)
        ),
        Category.FROZEN_FOODS to listOf(
            Product("Frozen Peas", "🫛", 0xFFC8E6C9),
            Product("Frozen Corn", "🌽", 0xFFFFF9C4),
            Product("Frozen Carrots", "🥕", 0xFFFFDAB9),
            Product("Frozen Broccoli", "🥦", 0xFFC8E6C9),
            Product("Frozen Spinach", "🥬", 0xFFC8E6C9),
            Product("Frozen Mixed Vegetables", "🥕", 0xFFC8E6C9),
            Product("Frozen Berries", "🫐", 0xFFD1C4E9),
            Product("Frozen Strawberries", "🍓", 0xFFFFCDD2),
            Product("Frozen Mango", "🥭", 0xFFFFE0B2),
            Product("Frozen Pineapple", "🍍", 0xFFFFFFE0),
            Product("Frozen Pizza", "🍕", 0xFFFFF9C4),
            Product("Frozen Chicken Nuggets", "🍗", 0xFFFFF3E0),
            Product("Frozen Fish Sticks", "🐟", 0xFFFFE0B2),
            Product("Frozen Fries", "🍟", 0xFFFFF9C4),
            Product("Frozen Tater Tots", "🥔", 0xFFFFF9C4),
            Product("Frozen Waffles", "🧇", 0xFFFFF3E0),
            Product("Frozen Pancakes", "🥞", 0xFFFFF3E0),
            Product("Frozen Breakfast Sandwich", "🥪", 0xFFFFF3E0),
            Product("Frozen Burritos", "🌯", 0xFFFFF3E0),
            Product("Frozen Lasagna", "🍝", 0xFFFFF3E0),
            Product("Frozen Meatballs", "🍖", 0xFFFFCDD2),
            Product("Frozen Shrimp", "🍤", 0xFFFFE4C4),
            Product("Frozen Edamame", "🫛", 0xFFC8E6C9),
            Product("Ice Cream", "🍦", 0xFFFFFFFF),
            Product("Frozen Yogurt", "🍦", 0xFFFFFFFF),
            Product("Popsicles", "🍭", 0xFFBBDEFB),
            Product("Frozen Pie", "🥧", 0xFFFFE0B2),
            Product("Frozen Dumplings", "🥟", 0xFFFFF3E0),
            Product("Frozen Spring Rolls", "🥠", 0xFFFFE0B2),
            Product("Frozen Ice", "🧊", 0xFFBBDEFB)
        ),
        Category.BEVERAGES to listOf(
            Product("Water", "💧", 0xFFBBDEFB),
            Product("Sparkling Water", "🫧", 0xFFBBDEFB),
            Product("Coffee", "☕", 0xFF795548),
            Product("Tea", "🍵", 0xFFC8E6C9),
            Product("Green Tea", "🍵", 0xFFC8E6C9),
            Product("Black Tea", "🍵", 0xFF795548),
            Product("Herbal Tea", "🍵", 0xFFFFCDD2),
            Product("Orange Juice", "🍊", 0xFFFFE0B2),
            Product("Apple Juice", "🍎", 0xFFFFCDD2),
            Product("Grape Juice", "🍇", 0xFFD1C4E9),
            Product("Cranberry Juice", "🫐", 0xFFFF5252),
            Product("Tomato Juice", "🍅", 0xFFFFC1C1),
            Product("Lemonade", "🍋", 0xFFFFF9C4),
            Product("Iced Tea", "🧊", 0xFFC8E6C9),
            Product("Soda", "🥤", 0xFFBBDEFB),
            Product("Cola", "🥤", 0xFF4E342E),
            Product("Ginger Ale", "🥤", 0xFFFFF9C4),
            Product("Root Beer", "🥤", 0xFF795548),
            Product("Energy Drink", "🥫", 0xFFBBDEFB),
            Product("Sports Drink", "🏋️", 0xFFBBDEFB),
            Product("Coconut Water", "🥥", 0xFFFFF5E6),
            Product("Almond Milk", "🥛", 0xFFFFF5E6),
            Product("Soy Milk", "🥛", 0xFFFFF5E6),
            Product("Oat Milk", "🥛", 0xFFFFF5E6),
            Product("Beer", "🍺", 0xFFFFF9C4),
            Product("Wine", "🍷", 0xFF8E24AA),
            Product("Champagne", "🍾", 0xFFFFF9C4),
            Product("Vodka", "🥃", 0xFFFFFFFF),
            Product("Whiskey", "🥃", 0xFFFFE0B2),
            Product("Rum", "🥃", 0xFFFFE0B2),
            Product("Tequila", "🥃", 0xFFFFFFFF),
            Product("Gin", "🍸", 0xFFFFFFFF)
        ),
        Category.HERBS_AND_SPICES to listOf(
            Product("Basil", "🌿", 0xFFC8E6C9),
            Product("Oregano", "🌿", 0xFFC8E6C9),
            Product("Rosemary", "🌿", 0xFFC8E6C9),
            Product("Thyme", "🌿", 0xFFC8E6C9),
            Product("Parsley", "🌿", 0xFFC8E6C9),
            Product("Cilantro", "🌿", 0xFFC8E6C9),
            Product("Mint", "🌿", 0xFFC8E6C9),
            Product("Dill", "🌿", 0xFFC8E6C9),
            Product("Chives", "🌿", 0xFFC8E6C9),
            Product("Sage", "🌿", 0xFFC8E6C9),
            Product("Bay Leaves", "🍃", 0xFFC8E6C9),
            Product("Paprika", "🌶️", 0xFFFF5252),
            Product("Smoked Paprika", "🌶️", 0xFFBF360C),
            Product("Chili Powder", "🌶️", 0xFFFF5252),
            Product("Cumin", "🧂", 0xFFD7CCC8),
            Product("Turmeric", "🧂", 0xFFFFF176),
            Product("Coriander", "🧂", 0xFFFFE0B2),
            Product("Cardamom", "🧂", 0xFFD7CCC8),
            Product("Cinnamon", "🧂", 0xFFD7CCC8),
            Product("Nutmeg", "🧂", 0xFFD7CCC8),
            Product("Cloves", "🧂", 0xFF4E342E),
            Product("Ginger", "🫚", 0xFFFFE0B2),
            Product("Garlic Powder", "🧄", 0xFFFFF5E6),
            Product("Onion Powder", "🧅", 0xFFFFF5E6),
            Product("Cayenne Pepper", "🌶️", 0xFFFF5252),
            Product("Red Pepper Flakes", "🌶️", 0xFFFF5252),
            Product("Black Peppercorns", "🧂", 0xFF4E342E),
            Product("White Pepper", "🧂", 0xFFFFF5E6),
            Product("Allspice", "🧂", 0xFFD7CCC8),
            Product("Fennel Seeds", "🧂", 0xFFFFE0B2),
            Product("Mustard Seeds", "🧂", 0xFFFFF176),
            Product("Saffron", "🧂", 0xFFFF9800),
            Product("Vanilla Bean", "🧂", 0xFF4E342E)
        ),
        Category.BREAD_AND_BAKERY to listOf(
            Product("White Bread", "🍞", 0xFFFFF3E0),
            Product("Whole Wheat Bread", "🍞", 0xFFFFE0B2),
            Product("Sourdough Bread", "🍞", 0xFFFFF3E0),
            Product("Rye Bread", "🍞", 0xFFD7CCC8),
            Product("Baguette", "🥖", 0xFFFFF3E0),
            Product("Ciabatta", "🍞", 0xFFFFF3E0),
            Product("Pita Bread", "🫓", 0xFFFFF3E0),
            Product("Naan", "🫓", 0xFFFFF3E0),
            Product("Tortillas", "🫓", 0xFFFFF3E0),
            Product("Bagels", "🥯", 0xFFFFF3E0),
            Product("English Muffins", "🍞", 0xFFFFF3E0),
            Product("Croissants", "🥐", 0xFFFFF3E0),
            Product("Dinner Rolls", "🍞", 0xFFFFF3E0),
            Product("Hamburger Buns", "🍔", 0xFFFFF3E0),
            Product("Hot Dog Buns", "🌭", 0xFFFFF3E0),
            Product("Sandwich Bread", "🍞", 0xFFFFF3E0),
            Product("Muffins", "🧁", 0xFFFFE0B2),
            Product("Donuts", "🍩", 0xFFFFF3E0),
            Product("Cakes", "🎂", 0xFFFFFFFF),
            Product("Cookies", "🍪", 0xFFFFE0B2),
            Product("Pie", "🥧", 0xFFFFE0B2),
            Product("Brownies", "🍫", 0xFF4E342E),
            Product("Cupcakes", "🧁", 0xFFFFFFFF),
            Product("Cinnamon Rolls", "🍞", 0xFFD7CCC8),
            Product("Breadsticks", "🥖", 0xFFFFF3E0),
            Product("Crackers", "🍘", 0xFFFFF3E0),
            Product("Pretzels", "🥨", 0xFFFFE0B2)
        )
    )
}

enum class Category(val displayName: String) {
    VEGETABLES("Vegetables"),
    FRUITS("Fruits"),
    DAIRY_AND_EGGS("Dairy and Eggs"),
    MEAT_AND_POULTRY("Meat and Poultry"),
    SEAFOOD("Seafood"),
    GRAINS_AND_LEGUMES("Grains and Legumes"),
    BAKING_AND_COOKING_ESSENTIALS("Baking and Cooking Essentials"),
    CONDIMENTS_AND_SAUCES("Condiments and Sauces"),
    SNACKS_AND_SWEETS("Snacks and Sweets"),
    CANNED_AND_PRESERVED_GOODS("Canned and Preserved Goods"),
    FROZEN_FOODS("Frozen Foods"),
    BEVERAGES("Beverages"),
    HERBS_AND_SPICES("Herbs and Spices"),
    BREAD_AND_BAKERY("Bread and Bakery")
}

@Serializable
data class Product(
    val name: String,
    val icon: String,
    val color: Long,
    val selected: Boolean = false
)